import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  TR: {
    // Sidebar & Navigation
    dashboard: "Gösterge Paneli",
    all_documents: "Tüm Belgeler",
    smart_contracts: "Akıllı Sözleşmeler",
    ai_anomalies: "AI Anomalileri",
    settings: "Ayarlar",
    network_status: "Ağ Durumu",
    system_active: "SİSTEM AKTİF",
    system_offline: "SİSTEM KAPALI",
    logout: "Çıkış Yap",
    individual_portal: "Bireysel Portal",
    secure_network: "Fintegrity Güvenli İşlem Ağı",
    theme_change: "Tema Değiştir",

    // General Buttons & Badges
    save: "Kaydet",
    cancel: "İptal",
    actions: "Aksiyonlar",
    status: "Durum",
    date: "Tarih",
    amount: "Tutar",
    sender: "Gönderici",
    verify: "Doğrula",
    verifying: "Doğrulanıyor...",
    verified: "Doğrulandı",
    pending: "Beklemede",
    approved: "Onaylandı",
    rejected: "Reddedildi",
    all: "Tümü",
    close: "Kapat",
    delete: "Sil",
    export: "Dışa Aktar",
    detail: "Detay",
    active: "Aktif",
    resolved: "Çözüldü",

    // Login Page
    login_title: "Fintegrity Giriş",
    login_subtitle: "Kurumsal Finans & Güvence Ağı",
    username: "Kullanıcı Adı",
    password: "Şifre",
    confirm_password: "Şifre Tekrar",
    remember_me: "Beni Hatırla",
    login_btn: "Giriş Yap",
    register_btn: "Kayıt Ol",
    register_prompt: "Hesabınız yok mu?",
    login_prompt: "Zaten hesabınız var mı?",
    register_title: "Hesap Oluştur",
    error_connection: "Sunucuya bağlanılamadı. Lütfen backend'in çalıştığından emin olun.",
    password_mismatch: "Şifreler uyuşmuyor.",
    login_network_active: "Güvenli Yönetim Ağı",
    login_network_register: "Yapay Zeka Destekli Kayıt Ağı",
    username_placeholder: "admin veya user",
    password_placeholder: "Şifrenizi yazın...",
    confirm_password_placeholder: "Şifrenizi tekrar yazın...",
    username_new_placeholder: "Yeni kullanıcı adı yazın...",
    register_success_msg: "Kayıt başarıyla tamamlandı! Giriş yapabilirsiniz.",
    register_failed_msg: "Kayıt işlemi başarısız oldu.",
    login_action_btn: "Sisteme Giriş Yap",
    create_new_account: "Yeni Hesap Oluştur (Kayıt Ol)",
    demo_accounts_title: "Test Hesapları:",

    // User Portal
    new_transfer: "Yeni Transfer",
    my_transactions: "İşlem Geçmişim",
    my_documents: "Belgelerim",
    wallet_balance: "Cüzdan Bakiyesi",
    transfer_title: "Para Transferi",
    transfer_subtitle: "Blockchain tabanlı güvenli ödeme ağı",
    receiver_address: "Alıcı Cüzdan / IBAN",
    amount_placeholder: "Gönderilecek Tutar (₺)",
    start_transfer: "Transferi Başlat",
    security_active: "Yapay Zeka destekli dolandırıcılık koruması aktiftir.",
    processing_security: "Güvenlik Taraması Yapılıyor...",
    tx_success: "İşlem Başarılı",
    tx_success_desc: "Transferiniz Fintegrity yapay zeka denetiminden başarıyla geçti ve blockchain ağına kaydedildi.",
    new_tx_btn: "Yeni İşlem Yap",
    last_transactions: "Son İşlemler",
    today: "Bugün",
    yesterday: "Dün",

    // Dashboard Page
    overview: "Genel Bakış",
    transactions_tab: "İşlemler",
    new_doc_scan: "Yeni Belge Tarama",
    audit_logs: "Denetim Logları",
    total_docs: "Toplam Belge",
    total_contracts: "Akıllı Sözleşme",
    anomalies_detected: "Tespit Edilen Anomali",
    live_tps: "Canlı TPS",
    blockchain_net_info: "Blockchain Ağ Bilgileri",
    connection_status: "Bağlantı Durumu",
    connected: "Bağlı",
    no_connection: "Bağlantı Yok",
    latest_block: "Son Blok",
    gas_price: "Gas Price",
    contract_addresses: "Kontrat Adresleri",
    recent_transactions: "Son İşlemler",
    ai_audit_scanner: "Yapay Zeka Denetim & Tarama Simülatörü",
    ai_scanner_desc: "Gerçek scikit-learn modelleri (IsolationForest & LogisticRegression) üzerinden test işlemi veya belge taraması gerçekleştirin.",
    amount_try: "İşlem Tutarı (₺)",
    account_id: "Hesap / Gönderici ID",
    doc_type: "Belge Türü",
    run_ai_scan: "Yapay Zeka Taramasını Çalıştır",
    scanning: "Taranıyor...",
    ai_scan_results: "Yapay Zeka Analiz Raporu (Açıklanabilir AI)",
    anomaly_status: "Anomali Durumu",
    anomaly_detected_alert: "ANOMALİ TESPİT EDİLDİ",
    normal_transaction_alert: "NORMAL İŞLEM",
    risk_score: "Risk Skoru",
    explanation: "Gerekçe / Açıklama",
    suggested_action: "Önerilen Aksiyon",
    model_used: "Kullanılan ML Modeli",
    weekly_hacim_title: "Haftalık İşlem Hacmi (₺)",
    detailed_report_btn: "Detaylı Rapor",
    scan_form_desc: "İşlemi anında test etmek için parametreleri ayarlayın veya formdaki gerçek verilerle analiz başlatın.",
    risk_criteria_title: "Risk Ölçüm Kriteri:",
    risk_criteria_desc: "Risk Skoru; işlem sıklığı, meblağ sapması ve tarihsel anomali paternlerine dayalı olarak ölçülmektedir.",
    realtime_output: "Gerçek Zamanlı Model Çıktısı",
    checking_blockchain: "Blockchain kayıtları doğrulanıyor...",
    feeding_ml_model: "IsolationForest modeline besleniyor...",
    risk_scoring_status: "Risk skorlaması...",
    risky_suspicious_tx: "RİSKLİ/ŞÜPHELİ İŞLEM",
    safe_tx: "GÜVENLİ İŞLEM",
    analyzed_amount: "Analiz Edilen Tutar",
    risk_score_threshold: "Risk Skoru / Eşik",
    ai_detection_reason: "AI Tespit Nedeni",
    normal_tx_bounds: "İşlem tutarı normal sınırlar içerisinde.",
    model_multipliers: "Model Karar Çarpanları:",
    multiplier_amount_history: "Tutar Geçmişi Uyumu",
    multiplier_network_trust: "Gönderici Ağı Güvenilirliği",
    multiplier_time_anomaly: "Zamanlama / Frekans Anomalisi",
    model_output_placeholder: "Sistemin ürettiği detaylı analiz logları ve risk skorları burada görüntülenecektir.",
    node_connection: "Düğüm Bağlantısı",
    status_ping: "Durum / Ping",
    network_metrics: "Ağ Metrikleri",
    latest_block_label: "En Son Blok",
    gas_price_label: "Gaz Fiyatı (Gas)",
    deployed_contracts_title: "Dağıtılan Akıllı Sözleşmeler (Smart Contracts)",
    core_contract_desc: "Belge hash'lerini ve metadata kayıtlarını immutable olarak saklar.",
    agreements_contract_desc: "Sözleşme yaşam döngüsünü (Oluşturma -> Onaylama -> Tamamlama) yönetir.",
    tx_details_title: "İşlem Detayı",
    tx_hash_label: "İşlem Hash'i",
    not_specified: "Belirtilmedi",
    analyze_with_ai_btn: "Bu İşlemi AI ile Analiz Et",
    weekly_report_title: "Haftalık Detaylı Rapor",
    date_day: "Tarih (Gün)",
    total_volume: "Toplam Hacim (₺)",
    reconciled: "Mutabık",
    csv_simulated_alert: "CSV İndirme işlemi simüle edildi.",
    download_report_btn: "Raporu İndir (.csv)",
    blockchain_desc_full: "e-Dönüşüm belge bütünlüğü ve iş akışları Ethereum Sanal Makinesi (EVM) uyumlu yerel düğüm üzerinde çalışan akıllı sözleşmelerle doğrulanır.",

    // Documents Page
    doc_panel_title: "e-Belge Yönetim Paneli",
    doc_panel_desc: "Blokzincir entegrasyonu ve AI sınıflandırması ile tüm fatura, irsaliye ve sözleşmeler.",
    upload_new_doc: "Yeni Belge Yükle",
    doc_text_input: "Belge Metni (AI Sınıflandırması İçin)",
    doc_text_placeholder: "Fatura bedeli, irsaliye detayları veya sözleşme maddelerini yazın...",
    document_hash: "Belge Hash Kodu",
    blockchain_verify: "Zincirde Doğrula",
    verify_success: "Doğrulandı",
    verify_mismatch: "Uyuşmazlık",
    verify_not_found: "Zincirde Kayıt Yok",
    verify_detail_db: "DB Hash",
    verify_detail_chain: "Chain Hash",
    doc_add_error: "Belge eklenemedi.",
    doc_status_error: "Belge durumu güncellenemedi.",
    doc_delete_confirm: "Bu belgeyi kalıcı olarak silmek istediğinize emin misiniz?",
    doc_delete_error: "Belge silinemedi.",
    doc_verify_error: "Doğrulama sırasında hata oluştu",
    search_doc_placeholder: "Belge ID veya Gönderici ara...",
    all_types: "Tüm Türler",
    sort_newest: "En Yeni",
    sort_oldest: "En Eski",
    sort_amount_high: "Tutar (Yüksekten Düşüğe)",
    sort_amount_low: "Tutar (Düşükten Yükseğe)",
    no_docs_found: "Seçilen filtrelere uygun belge bulunamadı.",
    details: "Detayları",
    blockchain_approved: "Blockchain Onaylı",
    not_available: "Mevcut değil",
    block_time: "Blok Zamanı",
    delete_document_btn: "Belgeyi Sil",
    document_type_label: "Belge Tipi",
    company_label: "Kurum",
    company_placeholder: "Örn: Tech Corp A.Ş.",
    save_and_submit: "Kaydet ve Gönder",

    // Contracts Page
    contracts_panel_title: "Akıllı Sözleşme Odası",
    contracts_panel_desc: "Tedarikçiler ve ortaklar arası dijital mutabakatlar ve Ethereum akıllı sözleşmeleri.",
    create_new_contract: "Yeni Sözleşme Oluştur",
    party_a: "Taraf A (Alıcı)",
    party_b: "Taraf B (Satıcı)",
    title: "Başlık",
    contract_details: "Sözleşme Detayları",
    parties: "Taraflar",
    sign_approve: "İmzala / Onayla",
    reject: "Reddet",
    complete_deal: "Sözleşmeyi Tamamla",
    tx_hash: "Zincir İşlem Hash",
    contract_status_error: "Durum güncellenemedi.",
    contract_add_error: "Sözleşme eklenemedi.",
    contract_value_label: "Değer",
    contract_details_title: "Sözleşme Detayı",
    agreement_parties_title: "Taraflar Arası Anlaşma",
    contract_type_label: "Sözleşme Tipi",
    supply_chain: "Tedarik Zinciri",
    staff_salary: "Personel Maaş",
    intl_b2b: "Uluslararası B2B",
    fleet_insurance: "Araç Filo Sigortası",
    property_rental: "Emlak Kira",
    party_1_label: "Taraf 1 (Gönderen/Yükleyici)",
    party_1_placeholder: "Örn: Lojistik A.Ş. veya Fintegrity HR",
    party_2_label: "Taraf 2 (Alıcı/Ortak)",
    party_2_placeholder: "Örn: Üretici Ltd. veya Çalışanlar",
    value_amount_label: "Değer / Tutar",
    value_amount_placeholder: "Örn: 125,000 ₺ veya $45,000",
    create_pending_btn: "Oluştur (Beklemede)",

    // Anomalies Page
    anomalies_panel_title: "AI Anomali Denetim Merkezi",
    anomalies_panel_desc: "IsolationForest yapay zeka modeli tarafından tespit edilen olağandışı finansal hareketler.",
    resolver: "Çözen Yetkili",
    resolve: "Çözüldü Olarak İşaretle",
    resolved_label: "Çözüldü",
    active_label: "Aktif",
    action_error: "İşlem sırasında bir hata oluştu.",
    search_id_org_placeholder: "ID veya Kurum ara...",
    all_levels: "Tüm Seviyeler",
    all_statuses: "Tüm Durumlar",
    anomaly_id: "Anomali ID",
    account_org: "Hesap / Kurum",
    level: "Seviye",
    action_col: "Eylem",
    inspect: "İncele",
    no_anomalies_found: "Seçilen filtrelere uygun anomali bulunamadı.",
    clear_filters: "Filtreleri Temizle",
    anomaly_review: "İncelemesi",
    risk_level: "Risk Seviyesi",
    ai_confidence_score: "Yapay Zeka Güven Skoru",
    related_transaction: "İlgili İşlem (TxHash)",
    mark_safe: "Güvenli İşaretle",
    freeze_transaction: "İşlemi Dondur",
    previously_resolved_msg: "Bu anomali daha önce '{status}' olarak işaretlenmiş.",

    // Settings Page
    settings_panel_title: "Sistem Ayarları",
    settings_panel_desc: "Kullanıcı profili ve arayüz özelleştirmeleri.",
    profile_info: "Profil Bilgileri",
    role: "Sistem Rolü",
    interface_settings: "Arayüz Ayarları",
    theme_label: "Arayüz Teması",
    theme_light: "Açık Tema",
    theme_dark: "Koyu Tema",
    theme_current: "Sistem Teması (Renkli)",
    save_settings: "Ayarları Kaydet",
    processing: "İşleniyor...",
    password_change_success: "Şifre başarıyla güncellendi.",
    password_change_error: "Şifre güncellenirken bir hata oluştu.",
    user_registering: "Kayıt yapılıyor...",
    user_register_success: "Kullanıcı başarıyla eklendi.",
    user_register_error: "Kullanıcı eklenirken bir hata oluştu.",
    theme_updating: "Tema güncelleniyor...",
    theme_success: "Tema başarıyla güncellendi.",
    theme_error: "Tema güncellenirken bir hata oluştu.",
    current_password: "Mevcut Şifre",
    new_password_label: "Yeni Şifre",
    update_password_btn: "Şifreyi Güncelle",
    appearance_settings: "Görünüm Ayarları",
    theme_default_desc: "Glassmorphism & Koyu Mod (Varsayılan)",
    theme_dark_desc: "Göz yormayan saf koyu tonlar",
    theme_light_desc: "Ferah ve parlak görünüm",
    add_new_user: "Yeni Kullanıcı Ekle",
    user_role: "Kullanıcı Rolü",
    standard_user: "Standart Kullanıcı",
    admin_user: "Yönetici (Admin)",
    user_password: "Kullanıcı Şifresi",
    admin_confirm_password_label: "İşlem Onayı İçin Kendi Şifreniz",
    admin_password_placeholder: "Admin Şifreniz",
    add_user_btn: "Kullanıcıyı Ekle",
    landing_hero_title: "Finansal Güvencede Yeni Nesil Blokzincir & Yapay Zeka Ağı",
    landing_hero_subtitle: "e-Dönüşüm belgelerinizi EVM uyumlu akıllı sözleşmelerle mühürleyin, şüpheli işlemleri yapay zeka modelleriyle anında tespit edin.",
    landing_get_started: "Sisteme Giriş Yap",
    landing_explore_features: "Özellikleri Keşfet",
    landing_feature_1_title: "Blokzincir Güvencesi",
    landing_feature_1_desc: "Tüm fatura, irsaliye ve makbuzların kriptografik özetleri (hash) zincire kaydedilir ve geriye dönük değiştirilemez hale gelir.",
    landing_feature_2_title: "Yapay Zeka Denetimi",
    landing_feature_2_desc: "IsolationForest makine öğrenmesi algoritmaları finansal verilerinizi tarar, anomalileri ve risk faktörlerini anında raporlar.",
    landing_feature_3_title: "Akıllı Mutabakatlar",
    landing_feature_3_desc: "Tedarikçiler ve iş ortakları arasındaki dijital anlaşmalar, Ethereum akıllı sözleşmeleri üzerinden otomatik olarak doğrulanır ve onaylanır.",
    landing_stats_title: "Fintegrity Canlı Ağ İstatistikleri",
    landing_stats_desc: "Platform üzerindeki işlemler ve blokzincir durum bilgileri anlık olarak güncellenmektedir.",
    landing_contact_support: "İletişim & Destek",
    back_to_home: "Ana Sayfaya Dön"
  },
  EN: {
    // Sidebar & Navigation
    dashboard: "Dashboard",
    all_documents: "All Documents",
    smart_contracts: "Smart Contracts",
    ai_anomalies: "AI Anomalies",
    settings: "Settings",
    network_status: "Network Status",
    system_active: "SYSTEM ACTIVE",
    system_offline: "SYSTEM OFFLINE",
    logout: "Log Out",
    individual_portal: "Individual Portal",
    secure_network: "Fintegrity Secure Transaction Network",
    theme_change: "Change Theme",

    // General Buttons & Badges
    save: "Save",
    cancel: "Cancel",
    actions: "Actions",
    status: "Status",
    date: "Date",
    amount: "Amount",
    sender: "Sender",
    verify: "Verify",
    verifying: "Verifying...",
    verified: "Verified",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    all: "All",
    close: "Close",
    delete: "Delete",
    export: "Export",
    detail: "Detail",
    active: "Active",
    resolved: "Resolved",

    // Login Page
    login_title: "Fintegrity Login",
    login_subtitle: "Enterprise Finance & Assurance Network",
    username: "Username",
    password: "Password",
    confirm_password: "Confirm Password",
    remember_me: "Remember Me",
    login_btn: "Log In",
    register_btn: "Register",
    register_prompt: "Don't have an account?",
    login_prompt: "Already have an account?",
    register_title: "Create Account",
    error_connection: "Failed to connect to the server. Please make sure the backend is running.",
    password_mismatch: "Passwords do not match.",
    login_network_active: "Secure Management Network",
    login_network_register: "AI-Powered Registration Network",
    username_placeholder: "admin or user",
    password_placeholder: "Enter your password...",
    confirm_password_placeholder: "Re-enter your password...",
    username_new_placeholder: "Enter new username...",
    register_success_msg: "Registration completed successfully! You can log in.",
    register_failed_msg: "Registration process failed.",
    login_action_btn: "Log In to System",
    create_new_account: "Create New Account (Register)",
    demo_accounts_title: "Test Accounts:",

    // User Portal
    new_transfer: "New Transfer",
    my_transactions: "My Transactions",
    my_documents: "My Documents",
    wallet_balance: "Wallet Balance",
    transfer_title: "Money Transfer",
    transfer_subtitle: "Blockchain-based secure payment network",
    receiver_address: "Recipient Wallet / IBAN",
    amount_placeholder: "Transfer Amount (₺)",
    start_transfer: "Start Transfer",
    security_active: "AI-powered fraud protection is active.",
    processing_security: "Performing Security Scan...",
    tx_success: "Transaction Successful",
    tx_success_desc: "Your transfer has successfully passed the Fintegrity AI scan and has been recorded on the blockchain.",
    new_tx_btn: "New Transaction",
    last_transactions: "Last Transactions",
    today: "Today",
    yesterday: "Yesterday",

    // Dashboard Page
    overview: "Overview",
    transactions_tab: "Transactions",
    new_doc_scan: "New Document Scan",
    audit_logs: "Audit Logs",
    total_docs: "Total Documents",
    total_contracts: "Smart Contracts",
    anomalies_detected: "Anomalies Detected",
    live_tps: "Live TPS",
    blockchain_net_info: "Blockchain Network Info",
    connection_status: "Connection Status",
    connected: "Connected",
    no_connection: "No Connection",
    latest_block: "Latest Block",
    gas_price: "Gas Price",
    contract_addresses: "Contract Addresses",
    recent_transactions: "Recent Transactions",
    ai_audit_scanner: "AI Audit & Scan Simulator",
    ai_scanner_desc: "Perform test transactions or document scans using real scikit-learn models (IsolationForest & LogisticRegression).",
    amount_try: "Transaction Amount (₺)",
    account_id: "Account / Sender ID",
    doc_type: "Document Type",
    run_ai_scan: "Run AI Audit Scan",
    scanning: "Scanning...",
    ai_scan_results: "AI Analysis Report (Explainable AI)",
    anomaly_status: "Anomaly Status",
    anomaly_detected_alert: "ANOMALY DETECTED",
    normal_transaction_alert: "NORMAL TRANSACTION",
    risk_score: "Risk Score",
    explanation: "Reason / Explanation",
    suggested_action: "Suggested Action",
    model_used: "Used ML Model",
    weekly_hacim_title: "Weekly Transaction Volume (₺)",
    detailed_report_btn: "Detailed Report",
    scan_form_desc: "Adjust parameters to test instantly or start analysis with real data.",
    risk_criteria_title: "Risk Assessment Criteria:",
    risk_criteria_desc: "Risk score is evaluated based on transaction frequency, amount deviation, and historical anomaly patterns.",
    realtime_output: "Real-Time Model Output",
    checking_blockchain: "Verifying blockchain records...",
    feeding_ml_model: "Feeding into IsolationForest model...",
    risk_scoring_status: "Risk scoring...",
    risky_suspicious_tx: "RISKY/SUSPICIOUS TRANSACTION",
    safe_tx: "SAFE TRANSACTION",
    analyzed_amount: "Analyzed Amount",
    risk_score_threshold: "Risk Score / Threshold",
    ai_detection_reason: "AI Detection Reason",
    normal_tx_bounds: "Transaction amount is within normal limits.",
    model_multipliers: "Model Decision Factors:",
    multiplier_amount_history: "Amount History Compatibility",
    multiplier_network_trust: "Sender Network Reliability",
    multiplier_time_anomaly: "Timing / Frequency Anomaly",
    model_output_placeholder: "Real-time analysis logs and risk scores generated by the system will be displayed here.",
    node_connection: "Node Connection",
    status_ping: "Status / Ping",
    network_metrics: "Network Metrics",
    latest_block_label: "Latest Block",
    gas_price_label: "Gas Price",
    deployed_contracts_title: "Deployed Smart Contracts",
    core_contract_desc: "Stores document hashes and metadata records immutably.",
    agreements_contract_desc: "Manages contract lifecycle (Creation -> Approval -> Completion).",
    tx_details_title: "Transaction Details",
    tx_hash_label: "Transaction Hash",
    not_specified: "Not Specified",
    analyze_with_ai_btn: "Analyze this Transaction with AI",
    weekly_report_title: "Weekly Detailed Report",
    date_day: "Date (Day)",
    total_volume: "Total Volume (₺)",
    reconciled: "Reconciled",
    csv_simulated_alert: "CSV download simulated.",
    download_report_btn: "Download Report (.csv)",
    blockchain_desc_full: "e-Transformation document integrity and workflows are verified by smart contracts running on an EVM compatible local node.",

    // Documents Page
    doc_panel_title: "e-Document Management Panel",
    doc_panel_desc: "All invoices, waybills, and contracts with blockchain integration and AI classification.",
    upload_new_doc: "Upload New Document",
    doc_text_input: "Document Text (For AI Classification)",
    doc_text_placeholder: "Enter invoice details, delivery notes, or contract clauses...",
    document_hash: "Document Hash Code",
    blockchain_verify: "Verify on Chain",
    verify_success: "Verified",
    verify_mismatch: "Mismatch",
    verify_not_found: "No Record on Chain",
    verify_detail_db: "DB Hash",
    verify_detail_chain: "Chain Hash",
    doc_add_error: "Failed to add document.",
    doc_status_error: "Failed to update document status.",
    doc_delete_confirm: "Are you sure you want to permanently delete this document?",
    doc_delete_error: "Failed to delete document.",
    doc_verify_error: "An error occurred during verification",
    search_doc_placeholder: "Search Document ID or Sender...",
    all_types: "All Types",
    sort_newest: "Newest",
    sort_oldest: "Oldest",
    sort_amount_high: "Amount (High to Low)",
    sort_amount_low: "Amount (Low to High)",
    no_docs_found: "No document found matching selected filters.",
    details: "Details",
    blockchain_approved: "Blockchain Approved",
    not_available: "Not available",
    block_time: "Block Time",
    delete_document_btn: "Delete Document",
    document_type_label: "Document Type",
    company_label: "Company",
    company_placeholder: "e.g. Tech Corp Inc.",
    save_and_submit: "Save and Submit",

    // Contracts Page
    contracts_panel_title: "Smart Contract Room",
    contracts_panel_desc: "Digital reconciliations and Ethereum smart contracts between suppliers and partners.",
    create_new_contract: "Create New Contract",
    party_a: "Party A (Buyer)",
    party_b: "Party B (Seller)",
    title: "Title",
    contract_details: "Contract Details",
    parties: "Parties",
    sign_approve: "Sign / Approve",
    reject: "Reject",
    complete_deal: "Complete Contract",
    tx_hash: "Chain Transaction Hash",
    contract_status_error: "Failed to update status.",
    contract_add_error: "Failed to add contract.",
    contract_value_label: "Value",
    contract_details_title: "Contract Details",
    agreement_parties_title: "Agreement Between Parties",
    contract_type_label: "Contract Type",
    supply_chain: "Supply Chain",
    staff_salary: "Staff Salary",
    intl_b2b: "International B2B",
    fleet_insurance: "Vehicle Fleet Insurance",
    property_rental: "Property Rental",
    party_1_label: "Party 1 (Sender/Uploader)",
    party_1_placeholder: "e.g. Logistics Inc. or Fintegrity HR",
    party_2_label: "Party 2 (Recipient/Partner)",
    party_2_placeholder: "e.g. Manufacturer Ltd. or Employees",
    value_amount_label: "Value / Amount",
    value_amount_placeholder: "e.g. 125,000 ₺ or $45,000",
    create_pending_btn: "Create (Pending)",

    // Anomalies Page
    anomalies_panel_title: "AI Anomaly Control Center",
    anomalies_panel_desc: "Unusual financial movements detected by the IsolationForest machine learning model.",
    resolver: "Resolved By",
    resolve: "Mark as Resolved",
    resolved_label: "Resolved",
    active_label: "Active",
    action_error: "An error occurred during processing.",
    search_id_org_placeholder: "Search ID or Company...",
    all_levels: "All Levels",
    all_statuses: "All Statuses",
    anomaly_id: "Anomaly ID",
    account_org: "Account / Org",
    level: "Level",
    action_col: "Actions",
    inspect: "Inspect",
    no_anomalies_found: "No anomaly found matching selected filters.",
    clear_filters: "Clear Filters",
    anomaly_review: "Review",
    risk_level: "Risk Level",
    ai_confidence_score: "AI Confidence Score",
    related_transaction: "Related Transaction (TxHash)",
    mark_safe: "Mark as Safe",
    freeze_transaction: "Freeze Transaction",
    previously_resolved_msg: "This anomaly was previously marked as '{status}'.",

    // Settings Page
    settings_panel_title: "System Settings",
    settings_panel_desc: "User profile and interface customizations.",
    profile_info: "Profile Info",
    role: "System Role",
    interface_settings: "Interface Settings",
    theme_label: "UI Theme",
    theme_light: "Light Theme",
    theme_dark: "Dark Theme",
    theme_current: "System Theme (Color)",
    save_settings: "Save Settings",
    processing: "Processing...",
    password_change_success: "Password updated successfully.",
    password_change_error: "An error occurred while updating the password.",
    user_registering: "Registering...",
    user_register_success: "User added successfully.",
    user_register_error: "An error occurred while adding the user.",
    theme_updating: "Updating theme...",
    theme_success: "Theme updated successfully.",
    theme_error: "An error occurred while updating the theme.",
    current_password: "Current Password",
    new_password_label: "New Password",
    update_password_btn: "Update Password",
    appearance_settings: "Appearance Settings",
    theme_default_desc: "Glassmorphism & Dark Mode (Default)",
    theme_dark_desc: "Comfortable pure dark tones",
    theme_light_desc: "Fresh and bright look",
    add_new_user: "Add New User",
    user_role: "User Role",
    standard_user: "Standard User",
    admin_user: "Administrator (Admin)",
    user_password: "User Password",
    admin_confirm_password_label: "Your Own Password for Approval",
    admin_password_placeholder: "Admin Password",
    add_user_btn: "Add User",
    landing_hero_title: "Next-Gen Blockchain & AI Network in Financial Assurance",
    landing_hero_subtitle: "Seal your e-transformation documents with EVM-compatible smart contracts, and detect suspicious transactions instantly using machine learning models.",
    landing_get_started: "Access System",
    landing_explore_features: "Explore Features",
    landing_feature_1_title: "Blockchain Security",
    landing_feature_1_desc: "Cryptographic hashes of all invoices, waybills, and receipts are recorded on the chain, making them immutably tamper-proof.",
    landing_feature_2_title: "AI Auditing & Detection",
    landing_feature_2_desc: "IsolationForest machine learning algorithms scan your financial records and report anomalies and risk factors in real-time.",
    landing_feature_3_title: "Smart Settlements",
    landing_feature_3_desc: "Digital agreements between suppliers and business partners are automatically verified and approved via Ethereum smart contracts.",
    landing_stats_title: "Fintegrity Live Network Statistics",
    landing_stats_desc: "Transactions and blockchain status metrics on the platform are updated in real-time.",
    landing_contact_support: "Contact & Support",
    back_to_home: "Back to Home Page"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'TR');

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('lang', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
